# Makefile for Fortran subroutines
# Regular: gfortran -o geometries.o -fbounds-check -shared -fPIC -O3 geometries.f90
# Debug: gfortran -o geometries.o -fbounds-check -shared -fPIC -Og geometries.f90

geometries.o: geometries.f90
	gfortran -o geometries.o -fbounds-check -shared -fPIC -O3 geometries.f90